/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.guessgame;

import id.co.indocyber.guessgame.model.WordModel;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

/**
 *
 * @author user
 */
public class GuessingGame extends javax.swing.JFrame {
    
  
        WordModel modelWord;
    //String[] bankSoal = {"Pondok Indah", "Sudirman", "Tugu Tani","Citos","Gandaria City"};
//        WordModel soal1 = new WordModel("Pondok Indah","Daerah di Jakarta Selatan");
//        WordModel soal2 = new WordModel("Sudirman","Jalan utama di Jakarta");
//        WordModel soal3 = new WordModel("Tugu Tani","Patung dekat Monas");
//        WordModel soal4 = new WordModel("Citos","Mall di Selatan Jakarta");
//        WordModel soal5 = new WordModel("Gandaria City","Mall anak muda");
        List<WordModel> bankSoal;
        
//        bankSoal.add(soal1);
//        bankSoal.add(soal2);
//        bankSoal.add(soal3);
//        bankSoal.add(soal4);
//        bankSoal.add(soal5);
    /**
     * Creates new form GuessingGame
     */
    public GuessingGame() {
        bankSoal = WordQuestionGenerator.CreateQuestionCollection();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        soalTextField = new javax.swing.JTextField();
        jawabanTextField = new javax.swing.JTextField();
        checkAnswerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jawabanLabel = new javax.swing.JLabel();
        mulaiButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        hintButton = new javax.swing.JButton();
        hintLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        soalTextField.setEditable(false);
        soalTextField.setForeground(new java.awt.Color(0, 51, 255));

        jawabanTextField.setForeground(new java.awt.Color(0, 51, 255));

        checkAnswerButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        checkAnswerButton.setForeground(new java.awt.Color(0, 51, 255));
        checkAnswerButton.setText("Periksa");
        checkAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAnswerButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Jawaban : ");

        jawabanLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jawabanLabel.setForeground(new java.awt.Color(0, 51, 255));
        jawabanLabel.setText("Belum ada jawaban");

        mulaiButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mulaiButton.setForeground(new java.awt.Color(0, 51, 255));
        mulaiButton.setText("Mulai");
        mulaiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mulaiButtonActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kota", "Buah-Buahan", "Mall", "Nama Binatang", "Dll" }));

        hintButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hintButton.setForeground(new java.awt.Color(0, 51, 255));
        hintButton.setText("Bantu Dong");
        hintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hintButtonActionPerformed(evt);
            }
        });

        hintLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        hintLabel.setForeground(new java.awt.Color(0, 51, 255));
        hintLabel.setText("Hint : ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(soalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jawabanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkAnswerButton)
                    .addComponent(jawabanLabel))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(mulaiButton)
                        .addGap(31, 31, 31)
                        .addComponent(hintButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(hintLabel)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mulaiButton)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hintButton))
                .addGap(18, 18, 18)
                .addComponent(hintLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(soalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jawabanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(checkAnswerButton)
                .addGap(18, 18, 18)
                .addComponent(jawabanLabel)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mulaiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mulaiButtonActionPerformed
        // TODO add your handling code here:
        int soalIndex = (int) Math.floor(Math.random() * bankSoal.size()); //floor untuk dibulatkan ke bawah jadi dapat mengambil index 0
        modelWord = bankSoal.get(soalIndex);
        soalTextField.setText(modelWord.acakHuruf());
        
        
//        basicWord = basicWord.toUpperCase();
//        String[] arrayOfWord = basicWord.split(""); 
//        
////        System.out.println("Huruf ke 2: " + arrayOfWord[1]);
//        
//        for (int i = 0; i < arrayOfWord.length; i++) {
//            System.out.println(arrayOfWord[i]);
//        }
//        
//        Arrays.sort(arrayOfWord); //mengurutkan isi arrayOfWord
//        StringBuilder sb = new StringBuilder(); //menggabungkan string
//        System.out.println("\nSetelah disort\n");
//        
//        for (int i = 0; i < arrayOfWord.length; i++) {
////            System.out.println(arrayOfWord[i]);           
//            sb.append(arrayOfWord[i]);
//        }
//        
//        String soal = sb.toString();
//        System.out.println("Soal yang harus di jawab: " + soal.trim());
//        soalTextField.setText(soal.trim());
    }//GEN-LAST:event_mulaiButtonActionPerformed

    private void checkAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAnswerButtonActionPerformed
        // TODO add your handling code here:
        String jawaban = jawabanTextField.getText().trim();
        modelWord.setJawaban(jawaban);
        if(modelWord.cekJawaban()){
            jawabanLabel.setText("Jenius");
        }
        else {
            jawabanLabel.setText("Coba Lagi");
        }
    }//GEN-LAST:event_checkAnswerButtonActionPerformed

    private void hintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hintButtonActionPerformed
        // TODO add your handling code here:
        hintLabel.setText(modelWord.getHint());
    }//GEN-LAST:event_hintButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessingGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkAnswerButton;
    private javax.swing.JButton hintButton;
    private javax.swing.JLabel hintLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jawabanLabel;
    private javax.swing.JTextField jawabanTextField;
    private javax.swing.JButton mulaiButton;
    private javax.swing.JTextField soalTextField;
    // End of variables declaration//GEN-END:variables
}
